### ISSUE TITLE
object temp_curve not found

### ISSUE THREAD

**Issue by japhir** [MartinSchobben/timemachine#1]
Looks cool! I'm interested, so I tried it out!

Installation works fine.

``` r
timemachine::timemachine_app()
Error: 'timemachine_app' is not an exported object from 'namespace:timemachine'
```
first of all, apparantly the function has a captial A somehow but the README refers to lowercase a?

then when I try to run the correct one:
``` r
timemachine::timemachine_App()
Loading required package: shiny

Listening on http://127.0.0.1:6475
Warning: Error in pull: object 'temp_curve' not found
  [No stack trace available]
Warning: Error in pull: object 'temp_curve' not found
  193: <Anonymous>
Warning: Error in pull: object 'temp_curve' not found
  193: <Anonymous>
```

and it looks like so:
![2020-11-17-14:24:03_region](https://user-images.githubusercontent.com/10659193/99395406-a884e880-28e0-11eb-9913-339dec0dddb6.png)

**Comment by MartinSchobben** [comment]
Can you try once more whether it works. I think I fixed it.

**Comment by japhir** [comment]
Works now! Great stuff!

It's pretty hard to zoom in on the present-day, but I guess that's sort of the message of the compilation ;-).

nitpick: Myr is usually used to indicate a time period, Ma for a specific time. So I think in these plots you need Ma in stead of Mya. Also because ~~some people like to think~~ it corresponds to Mega annum ~~(which is wrong, but a nice mnemonic)~~. Or just type out Million years ago.

**Comment by MartinSchobben** [comment]
The second tab shows the present/future in more detail. Both Mya and Ma ar fine (e.g. PNAS has the former and Nature the second as housstyle).

**Comment by japhir** [comment]
Ok, I remember googling this endlessly during my MSc and ultimately finding [this paper by Aubry et al., 2009](https://www.ldeo.columbia.edu/~ncb/Selected_Articles_all_files/25_Stratigraphy.6.100.pdf
) that convinced me. But I guess it's not standard in that case. 
Anyhow, I'll go ahead and close this :)
